// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//go:build obi_bpf_ignore
#include <bpfcore/vmlinux.h>
#include <bpfcore/bpf_helpers.h>
#include <bpfcore/bpf_core_read.h>

#include <statsolly/cgroup_names.h>
#include <statsolly/disk_attrs.h>
#include <statsolly/disk_accum.h>
#include <statsolly/disk_io.h>
#include <statsolly/types.h>
#include <statsolly/maps/disk_io_accum.h>
#include <statsolly/maps/disk_rq_start.h>
#include <statsolly/maps/disk_timed_queues.h>

// Set when block_rq_complete reports a blk_status_t (Linux 5.16+) instead of a negative errno.
volatile const bool disk_status_is_blk_status;
// The RQF_FLUSH_SEQ flag of struct request, which userspace finds in the kernel BTF: its bit
// depends on the kernel version, and some kernels number it in an anonymous enum.
volatile const u32 disk_rqf_flush_seq;
// The RQF_IO_STAT flag of struct request, which userspace finds in the kernel BTF: 0 where the
// kernel numbers its request flags with macros.
volatile const u32 disk_rqf_io_stat;

// Force structs into the ELF for automatic creation of Golang struct
const disk_io_key_t *unused_disk_io_key __attribute__((unused));
const disk_io_accum_t *unused_disk_io_accum __attribute__((unused));
const disk_cgroup_name_t *unused_disk_cgroup_name __attribute__((unused));

// The partitions of kernels before Linux 5.11 (including RHEL 8), which requests pointed to
// instead of a struct block_device
struct hd_struct___old {
    int partno;
} __attribute__((preserve_access_index));

struct request___old {
    struct hd_struct___old *part;
} __attribute__((preserve_access_index));

static __always_inline enum disk_op request_op(struct request *rq) {
    return disk_op_from_req_op(BPF_CORE_READ(rq, cmd_flags) & k_op_mask, disk_req_op_zone_append);
}

static __always_inline struct gendisk *request_disk(struct request *rq) {
    // rq->rq_disk was removed in Linux 5.17 in favor of rq->q->disk, which older kernels
    // (including RHEL 8) don't have.
    if (bpf_core_field_exists(rq->rq_disk)) {
        return BPF_CORE_READ(rq, rq_disk);
    }
    return BPF_CORE_READ(rq, q, disk);
}

// The cgroup the request is charged to: the io controller cgroup of its first bio, which the
// kernel also uses for io.stat and io.max. Requests generated by the block layer itself, such as
// flushes, have no bio.
static __always_inline struct cgroup *request_cgroup(struct request *rq) {
    return bio_cgroup(BPF_CORE_READ(rq, bio));
}

// The partition that the request targets: its dev_t, or its partition number on kernels before
// Linux 5.11.
static __always_inline void request_partition(struct request *rq, u32 *part_dev, u8 *partno) {
    struct bio *bio = BPF_CORE_READ(rq, bio);
    // Linux 5.12+: the block device of the first bio. Requests that the block layer generates,
    // such as flushes, have no bio.
    if (bpf_core_field_exists(bio->bi_bdev)) {
        if (bio) {
            *part_dev = BPF_CORE_READ(bio, bi_bdev, bd_dev);
        }
        return;
    }
    // Older kernels clear the partition of bios when they remap them to the whole disk, but
    // record the partition of requests in rq->part when the disk keeps I/O statistics
    if (bpf_core_field_exists(((struct hd_struct___old *)0)->partno)) {
        const struct request___old *old = (const void *)rq;
        *partno = BPF_CORE_READ(old, part, partno);
        return;
    }
    // Linux 5.11, where rq->part is already a struct block_device
    *part_dev = BPF_CORE_READ(rq, part, bd_dev);
}

// request_start_ns is when the kernel started timing a request, or 0 if it didn't. rq_flags is only
// read on the kernels that need it.
static __always_inline u64 request_start_ns(struct request *rq) {
    const u64 start_ns = BPF_CORE_READ(rq, start_time_ns);
    if (disk_rqf_io_stat == 0) {
        return start_ns;
    }
    return disk_accounted_start_ns(start_ns, BPF_CORE_READ(rq, rq_flags), disk_rqf_io_stat);
}

// request_queue_key is the key of the queue of a request in disk_timed_queues
static __always_inline u64 request_queue_key(struct request *rq) {
    return (u64)(uintptr_t)BPF_CORE_READ(rq, q);
}

// in_flush_sequence tells whether a request is a step of a flush sequence: the flush that the
// sequence issues, or a write with a cache flush before or after it, which the kernel completes
// once for its data and again at the end of the sequence
static __always_inline bool in_flush_sequence(struct request *rq) {
    return (BPF_CORE_READ(rq, rq_flags) & disk_rqf_flush_seq) != 0;
}

// never_issued tells whether a request completes without having been issued to the device, as
// the empty flush of an fsync does when the flush machinery completes it after the flush it
// waited for
static __always_inline bool never_issued(struct request *rq) {
    if (!bpf_core_field_exists(rq->state)) {
        return false;
    }
    return BPF_CORE_READ(rq, state) == bpf_core_enum_value(enum mq_rq_state, MQ_RQ_IDLE);
}

// kernel_times_requests tells whether the kernel records the issue time and the size of the
// requests (rq->io_start_time_ns and rq->stats_sectors): when the queue collects I/O statistics,
// which writeback throttling turns on by default. The kernel only decides after block_rq_issue,
// so this relies on what the completions of the queue found (see disk_timed_queues).
static __always_inline bool kernel_times_requests(struct request *rq) {
    // before Linux 5.5 (including RHEL 8), the kernel doesn't record the size
    if (!bpf_core_field_exists(rq->stats_sectors)) {
        return false;
    }
    const u64 queue = request_queue_key(rq);
    return bpf_map_lookup_elem(&disk_timed_queues, &queue) != 0;
}

static __always_inline void record_issue(struct request *rq) {
    if (kernel_times_requests(rq)) {
        return;
    }
    const enum disk_op op = request_op(rq);
    if (op == disk_op_unknown) {
        return;
    }
    const u64 issued_ns = bpf_ktime_get_ns();
    struct gendisk *disk = request_disk(rq);
    const u64 key = (u64)(uintptr_t)rq;
    const disk_rq_start_t start = {
        .issued_ns = issued_ns,
        .queued_ns = disk_queue_ns(request_start_ns(rq), issued_ns),
        .bytes = BPF_CORE_READ(rq, __data_len),
        .major = BPF_CORE_READ(disk, major),
        .minor = BPF_CORE_READ(disk, first_minor),
        .op = op,
    };
    bpf_map_update_elem(&disk_rq_start, &key, &start, BPF_ANY);
}

// Block layer tracepoint arguments changed in Linux 5.11 (also backported to 5.10.137+ and
// RHEL 8.6+): block_rq_issue went from (q, rq) to (rq). Userspace loads one of the two
// programs below after checking the tracepoint prototype in the kernel BTF.
SEC("raw_tracepoint/block_rq_issue")
int obi_stats_raw_tp_block_rq_issue(struct bpf_raw_tracepoint_args *ctx) {
    record_issue((struct request *)ctx->args[0]);
    return 0;
}

SEC("raw_tracepoint/block_rq_issue")
int obi_stats_raw_tp_block_rq_issue_legacy(struct bpf_raw_tracepoint_args *ctx) {
    record_issue((struct request *)ctx->args[1]);
    return 0;
}

// kernel_timed_start fills start from what the kernel recorded at the issue of a request that it
// timed, and adds its queue to disk_timed_queues so that the next requests of the queue are not
// recorded at their issue
static __always_inline bool
kernel_timed_start(struct request *rq, const u32 completed_bytes, disk_rq_start_t *start) {
    if (!bpf_core_field_exists(rq->stats_sectors)) {
        return false;
    }
    // the kernel zeroes it when it allocates or reinitializes a request
    const u64 issued_ns = BPF_CORE_READ(rq, io_start_time_ns);
    if (issued_ns == 0) {
        return false;
    }
    const u64 queue = request_queue_key(rq);
    if (!bpf_map_lookup_elem(&disk_timed_queues, &queue)) {
        const u8 timed = 1;
        bpf_map_update_elem(&disk_timed_queues, &queue, &timed, BPF_ANY);
    }
    struct gendisk *disk = request_disk(rq);
    start->issued_ns = issued_ns;
    start->queued_ns = disk_queue_ns(request_start_ns(rq), issued_ns);
    start->bytes = disk_rq_bytes(completed_bytes, BPF_CORE_READ(rq, stats_sectors));
    start->major = BPF_CORE_READ(disk, major);
    start->minor = BPF_CORE_READ(disk, first_minor);
    start->op = request_op(rq);
    return true;
}

// recorded_start moves what record_issue recorded of a request into start. A request that was
// not recorded was issued before the probes were attached or, if the kernel timed its queue,
// after the kernel stopped timing it: the queue is removed from disk_timed_queues so that its
// next requests are recorded.
static __always_inline bool recorded_start(struct request *rq, disk_rq_start_t *start) {
    const u64 rq_key = (u64)(uintptr_t)rq;
    const disk_rq_start_t *recorded = bpf_map_lookup_elem(&disk_rq_start, &rq_key);
    // what was recorded before the request started being timed belongs to an earlier request at
    // the same address, which the kernel timed. A start left by an earlier use (see
    // disk_accounted_start_ns) is older than this use, so it can only miss such a record.
    const u64 started_ns = BPF_CORE_READ(rq, start_time_ns);
    if (recorded && recorded->issued_ns < started_ns) {
        bpf_map_delete_elem(&disk_rq_start, &rq_key);
        recorded = 0;
    }
    if (!recorded) {
        if (bpf_core_field_exists(rq->stats_sectors)) {
            const u64 queue = request_queue_key(rq);
            bpf_map_delete_elem(&disk_timed_queues, &queue);
        }
        return false;
    }
    *start = *recorded;
    bpf_map_delete_elem(&disk_rq_start, &rq_key);
    return true;
}

// never_issued_start fills start for a request that was never issued: from when the kernel
// started timing it, as it also does in /proc/diskstats. The kernel doesn't count requests that it
// doesn't time.
static __always_inline bool
never_issued_start(struct request *rq, const u32 completed_bytes, disk_rq_start_t *start) {
    const u64 started_ns = request_start_ns(rq);
    if (started_ns == 0) {
        return false;
    }
    struct gendisk *disk = request_disk(rq);
    start->issued_ns = started_ns;
    start->queued_ns = k_disk_queue_unknown;
    start->bytes = completed_bytes;
    start->major = BPF_CORE_READ(disk, major);
    start->minor = BPF_CORE_READ(disk, first_minor);
    start->op = request_op(rq);
    return true;
}

SEC("raw_tracepoint/block_rq_complete")
int obi_stats_raw_tp_block_rq_complete(struct bpf_raw_tracepoint_args *ctx) {
    struct request *rq = (struct request *)ctx->args[0];
    const u8 status = disk_status_code(ctx->args[1], disk_status_is_blk_status);
    const u32 nr_bytes = (u32)ctx->args[2];

    if (!disk_rq_final_completion(nr_bytes, BPF_CORE_READ(rq, __data_len), status)) {
        return 0;
    }

    // the operations that OBI doesn't measure (passthrough, zone management) must not reach the
    // maps: from Linux 6.8 the kernel doesn't time passthrough commands, and their completion
    // would stop the timing of the queue
    const enum disk_op op = request_op(rq);
    if (op == disk_op_unknown) {
        return 0;
    }

    // the kernel completes a write with a cache flush before or after it again at the end of its
    // flush sequence, and only counts it then
    if (in_flush_sequence(rq) && op != disk_op_flush) {
        return 0;
    }

    // it was counted when its bytes completed
    if (disk_rq_completed_before(
            nr_bytes, op, BPF_CORE_READ(rq, bio) != 0, BPF_CORE_READ(rq, biotail) != 0)) {
        return 0;
    }

    disk_rq_start_t start = {};
    if (never_issued(rq)) {
        if (!never_issued_start(rq, nr_bytes, &start)) {
            return 0;
        }
    } else if (!kernel_timed_start(rq, nr_bytes, &start) && !recorded_start(rq, &start)) {
        return 0;
    }
    const u64 now_ns = bpf_ktime_get_ns();
    const u64 latency_ns = now_ns > start.issued_ns ? now_ns - start.issued_ns : 0;
    const u64 queued_ns = start.queued_ns;
    const u32 bytes = start.bytes;
    struct cgroup *cgrp = disk_read_cgroup ? request_cgroup(rq) : 0;
    disk_io_key_t key = {
        .cgroup_id = cgroup_id_of(cgrp),
        .major = start.major,
        .minor = start.minor,
        .op = start.op,
        .status = status,
    };
    if (disk_read_partition) {
        request_partition(rq, &key.part_dev, &key.partno);
    }

    disk_io_accum_t *accum = lookup_or_init_accum(&disk_io_accum, &key);
    if (!accum) {
        return 0;
    }
    if (cgrp) {
        record_cgroup_name(key.cgroup_id, cgrp);
    }
    if (status == 0) {
        __sync_fetch_and_add(&accum->bytes, bytes);
    }
    const u32 bucket =
        disk_latency_bucket(disk_latency_bounds_ns, disk_latency_bounds_len, latency_ns);
    if (bucket < k_disk_latency_max_buckets) {
        __sync_fetch_and_add(&accum->latency_count[bucket], 1);
        __sync_fetch_and_add(&accum->latency_sum_ns[bucket], latency_ns);
    }
    if (queued_ns == k_disk_queue_unknown) {
        return 0;
    }
    __sync_fetch_and_add(&accum->queue_ns, queued_ns);
    return 0;
}
