// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//go:build obi_bpf_ignore
#include <bpfcore/vmlinux.h>
#include <bpfcore/bpf_helpers.h>
#include <bpfcore/bpf_core_read.h>

#include <statsolly/cgroup_names.h>
#include <statsolly/disk_accum.h>
#include <statsolly/disk_io.h>
#include <statsolly/types.h>
#include <statsolly/maps/disk_io_accum.h>
#include <statsolly/maps/disk_rq_start.h>

// The request flags start right after the REQ_OP_BITS-wide operation field.
enum { k_req_op_mask = (1U << __REQ_FAILFAST_DEV) - 1 };

// Set when block_rq_complete reports a blk_status_t (Linux 5.16+) instead of a negative errno.
volatile const bool disk_status_is_blk_status;

// Force structs into the ELF for automatic creation of Golang struct
const disk_io_key_t *unused_disk_io_key __attribute__((unused));
const disk_io_accum_t *unused_disk_io_accum __attribute__((unused));
const disk_cgroup_name_t *unused_disk_cgroup_name __attribute__((unused));

// The partitions of kernels before Linux 5.11 (including RHEL 8), which requests pointed to
// instead of a struct block_device
struct hd_struct___old {
    int partno;
} __attribute__((preserve_access_index));

struct request___old {
    struct hd_struct___old *part;
} __attribute__((preserve_access_index));

static __always_inline enum disk_op request_op(struct request *rq) {
    return disk_op_from_req_op(BPF_CORE_READ(rq, cmd_flags) & k_req_op_mask);
}

static __always_inline struct gendisk *request_disk(struct request *rq) {
    // rq->rq_disk was removed in Linux 5.17 in favor of rq->q->disk, which older kernels
    // (including RHEL 8) don't have.
    if (bpf_core_field_exists(rq->rq_disk)) {
        return BPF_CORE_READ(rq, rq_disk);
    }
    return BPF_CORE_READ(rq, q, disk);
}

// The cgroup the request is charged to: the io controller cgroup of its first bio, which the
// kernel also uses for io.stat and io.max. Requests generated by the block layer itself, such as
// flushes, have no bio.
static __always_inline struct cgroup *request_cgroup(struct request *rq) {
    struct bio *bio = BPF_CORE_READ(rq, bio);
    if (!bio) {
        return 0;
    }
    return BPF_CORE_READ(bio, bi_blkg, blkcg, css.cgroup);
}

// The partition that the request targets: its dev_t, or its partition number on kernels before
// Linux 5.11.
static __always_inline void request_partition(struct request *rq, u32 *part_dev, u8 *partno) {
    struct bio *bio = BPF_CORE_READ(rq, bio);
    // Linux 5.12+: the block device of the first bio. Requests that the block layer generates,
    // such as flushes, have no bio.
    if (bpf_core_field_exists(bio->bi_bdev)) {
        if (bio) {
            *part_dev = BPF_CORE_READ(bio, bi_bdev, bd_dev);
        }
        return;
    }
    // Older kernels clear the partition of bios when they remap them to the whole disk, but
    // record the partition of requests in rq->part when the disk keeps I/O statistics
    if (bpf_core_field_exists(((struct hd_struct___old *)0)->partno)) {
        const struct request___old *old = (const void *)rq;
        *partno = BPF_CORE_READ(old, part, partno);
        return;
    }
    // Linux 5.11, where rq->part is already a struct block_device
    *part_dev = BPF_CORE_READ(rq, part, bd_dev);
}

static __always_inline void record_issue(struct request *rq) {
    const enum disk_op op = request_op(rq);
    if (op == disk_op_unknown) {
        return;
    }
    const u64 issued_ns = bpf_ktime_get_ns();
    struct gendisk *disk = request_disk(rq);
    const u64 key = (u64)(uintptr_t)rq;
    const disk_rq_start_t start = {
        .issued_ns = issued_ns,
        .queued_ns = disk_queue_ns(BPF_CORE_READ(rq, start_time_ns), issued_ns),
        .bytes = BPF_CORE_READ(rq, __data_len),
        .major = BPF_CORE_READ(disk, major),
        .minor = BPF_CORE_READ(disk, first_minor),
        .op = op,
    };
    bpf_map_update_elem(&disk_rq_start, &key, &start, BPF_ANY);
}

// Block layer tracepoint arguments changed in Linux 5.11 (also backported to 5.10.137+ and
// RHEL 8.6+): block_rq_issue went from (q, rq) to (rq). Userspace loads one of the two
// programs below after checking the tracepoint prototype in the kernel BTF.
SEC("raw_tracepoint/block_rq_issue")
int obi_stats_raw_tp_block_rq_issue(struct bpf_raw_tracepoint_args *ctx) {
    record_issue((struct request *)ctx->args[0]);
    return 0;
}

SEC("raw_tracepoint/block_rq_issue")
int obi_stats_raw_tp_block_rq_issue_legacy(struct bpf_raw_tracepoint_args *ctx) {
    record_issue((struct request *)ctx->args[1]);
    return 0;
}

SEC("raw_tracepoint/block_rq_complete")
int obi_stats_raw_tp_block_rq_complete(struct bpf_raw_tracepoint_args *ctx) {
    struct request *rq = (struct request *)ctx->args[0];
    const u8 status = disk_status_code(ctx->args[1], disk_status_is_blk_status);
    const u32 nr_bytes = (u32)ctx->args[2];

    if (!disk_rq_final_completion(nr_bytes, BPF_CORE_READ(rq, __data_len), status)) {
        return 0;
    }

    const u64 rq_key = (u64)(uintptr_t)rq;
    const disk_rq_start_t *start = bpf_map_lookup_elem(&disk_rq_start, &rq_key);
    if (!start) {
        return 0;
    }
    const u64 latency_ns = bpf_ktime_get_ns() - start->issued_ns;
    const u64 queued_ns = start->queued_ns;
    const u32 bytes = start->bytes;
    struct cgroup *cgrp = request_cgroup(rq);
    disk_io_key_t key = {
        .cgroup_id = BPF_CORE_READ(cgrp, kn, id),
        .major = start->major,
        .minor = start->minor,
        .op = start->op,
        .status = status,
    };
    bpf_map_delete_elem(&disk_rq_start, &rq_key);
    request_partition(rq, &key.part_dev, &key.partno);

    disk_io_accum_t *accum = lookup_or_init_accum(&disk_io_accum, &key);
    if (!accum) {
        return 0;
    }
    if (cgrp) {
        record_cgroup_name(key.cgroup_id, cgrp);
    }
    if (status == 0) {
        __sync_fetch_and_add(&accum->bytes, bytes);
    }
    const u32 bucket =
        disk_latency_bucket(disk_latency_bounds_ns, disk_latency_bounds_len, latency_ns);
    if (bucket < k_disk_latency_max_buckets) {
        __sync_fetch_and_add(&accum->latency_count[bucket], 1);
        __sync_fetch_and_add(&accum->latency_sum_ns[bucket], latency_ns);
    }
    if (queued_ns == k_disk_queue_unknown) {
        return 0;
    }
    const u32 queue_bucket =
        disk_latency_bucket(disk_latency_bounds_ns, disk_latency_bounds_len, queued_ns);
    if (queue_bucket < k_disk_latency_max_buckets) {
        __sync_fetch_and_add(&accum->queue_count[queue_bucket], 1);
        __sync_fetch_and_add(&accum->queue_sum_ns[queue_bucket], queued_ns);
    }
    return 0;
}
